### ISSUE TITLE
How can I control the buttons on the toolbar?

### ISSUE THREAD

**Issue by jeffreybraun** [psergus/ngWYSIWYG#10]
Hi, this looks like a great component, but I was curious how I can limit some of the buttons on the toolbar. I'm not suppose to provided this many options to our user-base. 

Thanks, 

Jeff

**Comment by psergus** [comment]
Good idea Jeff, I will work on it.

**Comment by psergus** [comment]
I added a config where you can provide which buttons and groups you want to show.

**Comment by brunokrebs** [comment]
Hi there @psergus, I'm using it already and it is working. Why don't you mark this as closed?

**Comment by psergus** [comment]
Thx @brunokrebs
