### ISSUE TITLE
There is a XSS in the process of model to view. 

### ISSUE THREAD

**Issue by anchengjian** [psergus/ngWYSIWYG#12]
There is a XSS in the process of model to view. <br>
Simple example：<br>
```html
<img src=x onerror=alert(/xss/) >
```
![XSS](http://i3.tietuku.com/ca66ab76a1973a92.png).<br>
Now, I have fixed the bug, and push it to my github. In that repertory, I have improved the ui of tinyEditor, and Chinesizated it.<br>
If you can, I want to be a branch of your ngWYSIWYG.<br>
My github: [ngTinyEditor](https://github.com/anchengjian/ngTinyEditor)<br>

**Comment by psergus** [comment]
thx for pointing this out. I will add fix.

On Wed, Sep 23, 2015 at 3:45 AM, anchengjian <notifications@github.com>
wrote:

> There is a XSS in the process of model to view.
>
> Simple example：
>
> <img src=x onerror=alert(/xss/) >
>
> [image: XSS]
> <https://camo.githubusercontent.com/6c6400ad71da09380d0dbaebff06c90d4ecde561/687474703a2f2f69332e74696574756b752e636f6d2f636136366162373661313937336139322e706e67>
> .
>
> Now, I have fixed the bug, and push it to my github. In that repertory, I
> have improved the ui of tinyEditor, and Chinesizated it.
>
> If you can, I want to be a branch of your ngWYSIWYG.
>
> My github: ngTinyEditor <https://github.com/anchengjian/ngTinyEditor>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psergus/ngWYSIWYG/issues/12>.
>



-- 
Best regards,
Sergey Petrenko

**Comment by psergus** [comment]
I added solution, which was very simple. thx again.
