### ISSUE TITLE
Add version tags

### ISSUE THREAD

**Issue by rjgarciadelpino** [psergus/ngWYSIWYG#15]
I want to use in my rails app through rails-assets.org

**Comment by psergus** [comment]
@rjgarciadelpino , there are version tags. If you do git tag, it will show you. Unless I don't see something :) Let me know please

**Comment by psergus** [comment]
Perhaps you meant this page: https://github.com/psergus/ngWYSIWYG/tags
However, this will appear when we have the first release. I guess it will happen soon when I add tests.

**Comment by rjgarciadelpino** [comment]
Ok! I thought it was production ready!

**Comment by psergus** [comment]
I use it on my production site. However, I would like to add testing suite before the public can accept it as a production ready. You know what I mean :)

**Comment by ashuorg** [comment]
@psergus perhaps you can start with beta versions v0.1 so that we don't keep changing our code to make it compatible with the directive upgrades

**Comment by psergus** [comment]
ashuorg, good idea. I will wrap it up and do asap

**Comment by psergus** [comment]
I did a release. Thx for the suggestion :)

On Thu, Dec 17, 2015 at 7:33 AM, Sergey Petrenko <sergey@inkfrog.com> wrote:

> ashuorg, good idea. I will wrap it up and do asap
>
> Sent from my iPhone
>
> On Dec 17, 2015, at 3:22 AM, ashuorg <notifications@github.com> wrote:
>
> @psergus <https://github.com/psergus> perhaps you can start with beta
> versions v0.1 so that we don't keep changing our code to make it compatible
> with the directive upgrades
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psergus/ngWYSIWYG/issues/15#issuecomment-165428220>.
>
>


-- 
Best regards,
Sergey Petrenko

**Comment by brunokrebs** [comment]
I have created a pull-request to help on dealing with tags, patchs, features and releases. Hopefully @psergus will accept it :+1: 

Besides that, since there is at least one tag already (v0.3.3), I think we can close this issue.
