### ISSUE TITLE
Layout in BODY tag not good practice

### ISSUE THREAD

**Issue by eugenev3** [psergus/ngWYSIWYG#18]
This can cause global issues when compiling the CSS if using a CSS preprocessor such as SASS.

**Comment by psergus** [comment]
explain pls

**Comment by eugenev3** [comment]
For anyone who wants to pull in ngWYSIWYG into their web app or web site, your BODY margin and padding definitions in editor.css can override their BODY styles. I don't think it is necessary in editor.css.

**Comment by psergus** [comment]
I see what you mean now. Completely agree. I just reworked styles to push them into the scope and avoid the space pollution. I also added sass file. Thx for your feedback. :+1:

**Comment by brunokrebs** [comment]
Issue solved? Maybe it is time to close it.

BTW: Sorry to keep bothering you @psergus, but I like this lib and I will be playing with it for a while.

**Comment by psergus** [comment]
closing it.
