### ISSUE TITLE
Sometimes caret disappears on Chrome

### ISSUE THREAD

**Issue by brunokrebs** [psergus/ngWYSIWYG#22]
This happens quite frequently and it is annoying but looks like it is really easy to solve.

**How to reproduce**

Open the [demo page](http://psergus.github.io/ngWYSIWYG/), remove all content, write something and then click somewhere else in the page. After that click on the editor again and the caret is not shown, even though it is possible to keep editing the content.

**Possible solution**

This [answer on stackoverflow's thread](http://stackoverflow.com/a/20250367/1232793) give a hint on how to solve this. By adding the following style to the iframe's document:

```css
html, body {
    height:100%;
}
```
everything works as expected.

**Comment by brunokrebs** [comment]
Well, actually I've found a better solution, which is the same one implemented by CKEditor to the issue opened there. Check out the following [merge on their repo](https://github.com/ckeditor/ckeditor-dev/commit/5d8d34a).

I will make a pull request with my solution.

**Comment by psergus** [comment]
@brunokrebs, thanks for much for helping man :+1:

**Comment by brunokrebs** [comment]
@psergus would you mind to release a patch with my fix?

**Comment by psergus** [comment]
@brunokrebs, yeah, should be already in the master repo. Please check it out. Let me know if something not right.

**Comment by brunokrebs** [comment]
You are right, @psergus, my fix is in the master repo already, but there is no new patch (i.e. no git tag) with my fix.

I was going to tell you that you need to bump it with bower, but I just saw that [bower.json](https://github.com/psergus/ngWYSIWYG/blob/master/bower.json#L3) has the wrong version. I'm going to fix it and send a pull request.

**Comment by psergus** [comment]
ahh, you are 100% right. Yea, sends the request and I will merge with the
master.

On Sun, Jan 10, 2016 at 10:08 AM, Bruno Krebs <notifications@github.com>
wrote:

> You are right, @psergus <https://github.com/psergus>, my fix is in the
> master repo already, but there is no new patch (i.e. no git tag) with my
> fix.
>
> I was going to tell you that you need to bump it with bower, but I just
> saw that bower.json
> <https://github.com/psergus/ngWYSIWYG/blob/master/bower.json#L3> has the
> wrong version. I'm going to fix it and send a pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psergus/ngWYSIWYG/issues/22#issuecomment-170375656>.
>



-- 
Best regards,
Sergey Petrenko
