### ISSUE TITLE
Source code indentation

### ISSUE THREAD

**Issue by brunokrebs** [psergus/ngWYSIWYG#32]
I have seen that there are some places that indentation is made with two empty spaces and other places they are made with tab. Would you mind if I fix all the source code to use tabs instead of two spaces?

I know that this is a personal choice and I have read a few articles about both of them, so to make it simple, tabs are more flexible. If you want it to look like two spaces, you just have to configure your IDE, if you want it to look bigger, the same applies.

And two spaces are, well, two spaces no matter what.

If you agree, @psergus, I will open a pull request to fix that.

Best regards,
Bruno Krebs

**Comment by psergus** [comment]
Hi Bruno,

yeah, of course - go ahead :+1:
