### ISSUE TITLE
When integrated in minified source code, there's an injection dependency error message. 

### ISSUE THREAD

**Issue by ferryarman** [psergus/ngWYSIWYG#37]
Hi, just want to report there's a bug on your ngWYSIWYG code.

Related file: js/wysiwyg.js

````javascript
line 61: $provide.decorator("$sanitize", function($delegate, $log) { ... }
````
I think you need to change it to:

````javascript
			$provide.decorator("$sanitize", ['$delegate', '$log', function($delegate, $log) {
				return function(text, target) {
					var result = $delegate(text, target);
					//$log.info("$sanitize input: " + text);
					//$log.info("$sanitize output: " + result);
					return result;
				};
			}]);
````

Caught the dependency error, by attaching ng-strict-di:
````html
<html ng-app="yourApp" ng-strict-di>
...
</html
````
Uncaught Error: [$injector:strictdi] function($delegate, $log) is not using explicit annotation and cannot be invoked in strict mode
http://errors.angularjs.org/1.4.8/$injector/strictdi?p0=function(%24delegate%2C%20%24log)

**Comment by psergus** [comment]
sorry about that. I posted a fix into the master.

**Comment by ferryarman** [comment]
Thanks Sergey for the fix, just FYI .. I think you forgot to update this file: 
dist/wysiwyg.min.js
