### ISSUE TITLE
Format doesn't change anything

### ISSUE THREAD

**Issue by chrillewoodz** [psergus/ngWYSIWYG#38]
What does 'format' actually do? You can set a paragraph and headers but they don't actually seem to be doing anything.. I can't see any change in the wysiwyg itself or in the source. Explanation please? :)

**Comment by brunokrebs** [comment]
Well, it is a bug :bug: 

I have seen this before, but since I don't use this button I didn't filed the issue nor solved it. But it seems quite easy to solve it.

**Comment by OlexandrPopov** [comment]
![style](https://cloud.githubusercontent.com/assets/1233052/12654719/1613a26a-c5fe-11e5-878c-27f6ba92f6a8.png)
Do you mean the dropdown shown on the attached screenshot?

**Comment by brunokrebs** [comment]
Exactly.

**Comment by OlexandrPopov** [comment]
I fixed it yesterday. Check it #43

**Comment by chrillewoodz** [comment]
Awesome :) Thanks.
