### ISSUE TITLE
Resize is not working properly

### ISSUE THREAD

**Issue by chrillewoodz** [psergus/ngWYSIWYG#39]
When you drag the resize down, it immediately jumps down to approximately twice the size of the editor before you started the resize, then you can resize it as usual. Is this really something no one has come across?

**Comment by OlexandrPopov** [comment]
I have similar issue in my project.

**Comment by OlexandrPopov** [comment]
The issue appears when your page has scroll bar. I created a test page http://popov.skyboxua.com/ngWYSIWYG/dev/

Steps to reproduce:
1. Open the page
2. Scroll down the page and try to resize the editor.

**Comment by brunokrebs** [comment]
Nice, this can help fixing it.

**Comment by OlexandrPopov** [comment]
Here is the function that is responsible for resize. As you can see it depends on $event.pageY. And in some cases (like on the example) $event.pageY may be a very large value. 

```
var resizeDown = function($event) {
	var margin = 50,
		uppest = $element[0].offsetTop + margin,
		height = $event.pageY > uppest ? $event.pageY - $element[0].offsetTop : margin;

	$element.css({
		height: height + "px"
	});
};
```

**Comment by brunokrebs** [comment]
Thanks @OlexandrPopov, I'm looking what we can do to solve this issue.

**Comment by brunokrebs** [comment]
Damn, this was harded than I was expecting. Anyway, now resizing button is working properly on Safari, Chrome, Firefox and IE (11 at least). I have added fixed a few issues, refactored the code to keep ngpResize directive on its own file, and added a feature to make window scroll while resizing down.

All this was release on [version v0.5.2](https://github.com/psergus/ngWYSIWYG/releases/tag/v0.5.2). Enjoy!

**Comment by OlexandrPopov** [comment]
Great job!

**Comment by psergus** [comment]
+1

On Sat, Jan 30, 2016 at 1:26 AM, Oleksandr Popov <notifications@github.com>
wrote:

> Great job!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psergus/ngWYSIWYG/issues/39#issuecomment-177124596>.
>



-- 
Best regards,
Sergey Petrenko
