### ISSUE TITLE
a lot of buttons won't work when screen width is narrow

### ISSUE THREAD

**Issue by butaixianran** [psergus/ngWYSIWYG#4]
A lot of buttons will leave the toolbar and won't work any more, when screen width is narrow

**Comment by psergus** [comment]
butaixianran, can you tell pls what width did you try?

**Comment by butaixianran** [comment]
I narrow my chrome 42 to mobile size. Here is a screenshot:

![2015-04-26 6-25-35](https://cloud.githubusercontent.com/assets/5558722/7335141/3255fd20-ebdd-11e4-9c83-91770f245645.jpg)

I also find a solution for that, we can update the template, add flex to toolbar's style, then it will be fine. But the gray image background will be mess, so I just remove it and use Bootstrap's class.

Check this:
http://plnkr.co/edit/Doz2qGP3dBljPUe4F23x?p=preview

**Comment by psergus** [comment]
good idea, let me play with it

On Sat, Apr 25, 2015 at 4:17 PM, butaixianran <notifications@github.com>
wrote:

> I narrow my chrome 42 to mobile size. Here is a screenshot:
>
> [image: 2015-04-26 6-25-35]
> <https://cloud.githubusercontent.com/assets/5558722/7335141/3255fd20-ebdd-11e4-9c83-91770f245645.jpg>
>
> I also find a solution for that, we can update the template, add flex to
> toolbar's style, then it will be fine. But the gray image background will
> be mess, so I just remove it and use Bootstrap's class.
>
> Check this:
> http://plnkr.co/edit/Doz2qGP3dBljPUe4F23x?p=preview
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psergus/ngWYSIWYG/issues/4#issuecomment-96290980>.
>



-- 
Best regards,
Sergey Petrenko

**Comment by psergus** [comment]
I updated CSS and regrouped some buttons so they are more responsive now to the screen size change. Thx for the notice :+1:

**Comment by brunokrebs** [comment]
I just tested it and your fix is working just fine @psergus. If @butaixianran has nothing new to add to this issue, I think it is a good time to close it.

**Comment by psergus** [comment]
closing it. thx @brunokrebs and @butaixianran
