### ISSUE TITLE
execCommand('insertHTML') dont work with IE

### ISSUE THREAD

**Issue by MegazeroMZ** [psergus/ngWYSIWYG#42]
So I have another problem here, I try the whole thing in IE 11 and all the function/button that require execCommand('insertHTML',val) like insert image, symbol all stop working. How do I get around this?

**Comment by brunokrebs** [comment]
Damn Microsoft, why don't they do a better job following standards. Hopefully this will work on Edge, but for now I have the following solution: http://stackoverflow.com/questions/6690752/insert-html-at-caret-in-a-contenteditable-div/6691294#6691294

**Comment by MegazeroMZ** [comment]
@brunokrebs surprisingly, IE 9 or lower have an alternative to insertHTML, Edge have insertHTML, only IE 10 and 11 for some reason remove it...

As for that solution, I found it already but I dont know how to apply it in.. I added the pasteHtmlAtCaret function into ngwysiwyg.js and try to call it from the insertImage function at the end of that file, but it didnt work. Looking at fiddle and I saw they have a getElementById('text').focus() before calling pasteHtmlAtCaret function, but I couldnt getElementById the body with contenteditable, I did added the id="text" into it in the ngwysiwyg.js, and when I inspect element the code I saw the id="text" on it, but getElementById always return null even if I ran the getElementById directly on the browser console after everything is loaded and I already saw the id in the DOM. So as of now after nearly 8 hours trying, I'm completely stuck and dont know how to do it :( If you can apply that solution to ngwysiwyg, can you tell me step by step how do you do that?

**Comment by brunokrebs** [comment]
I'm going to work on that now.

**Comment by brunokrebs** [comment]
Ok, @MegazeroMZ 

I have issued a [pull request with the solution](https://github.com/psergus/ngWYSIWYG/pull/45). Now you have two alternatives. First: you wait til @psergus accept my pull request (which usually doesn't take that long). Second: you use [insert-html branch in my own repo](https://github.com/brunokrebs/ngWYSIWYG/tree/insert-html).

If you follow the second approach (using my repo) and you use bower to manage your dependencies, then you can add a dependency to my repo with the following command:

```
bower install brunokrebs/ngWYSIWYG#insert-html --save
```

If you don't use bower, then just copy the [minified file](https://raw.githubusercontent.com/brunokrebs/ngWYSIWYG/insert-html/dist/wysiwyg.min.js).

**Comment by MegazeroMZ** [comment]
@brunokrebs thanks. I'm going to try that tomorrow and I will let you know what happen.

**Comment by psergus** [comment]
Merged the fix. Thx @brunokrebs and @MegazeroMZ

On Thu, Jan 28, 2016 at 6:41 AM, MegazeroMZ <notifications@github.com>
wrote:

> @brunokrebs <https://github.com/brunokrebs> thanks. I'm going to try that
> tomorrow and I will let you know what happen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psergus/ngWYSIWYG/issues/42#issuecomment-176213134>.
>



-- 
Best regards,
Sergey Petrenko

**Comment by MegazeroMZ** [comment]
Big thanks to btoh @brunokrebs  and @psergus . It's now work on IE. I want to add something too. For the insertImage by link it work fine since the focus never lost, but as what I do on the previous issue post about creating new button for uploading my own image using a modal, since the modal is called the focus on the iframe lost, so even when the upload work fine, the pasteHtmlAtCaret dont work since it dont have anything to focus into. So before pasteHtmlAtCaret it's still a good idea to do 

`loadVars();
iframeDocument.getElementById('testing').focus();`

before pasteHtmlAtCaret. It wont pasted the HTML at exactly where the caret use to be since focus again make caret position go back to 0 so it pasted on top of the text, but at least after that user can drag it ago to where they want.

This is only an issue with IE, for Chrome the focus dont lost at all when open modal, and if the focus is still there .focus() wont reset caret position, so everything is fine.

**Comment by MegazeroMZ** [comment]
I found a new bug, this time for all browser. After I insert a picture by link, the picture appear on the editor, but if I click on "source" at the bottom of ngWYSIWYG I saw nothing, the <img> line is not added yet, but the image still appear on the editor. it will only get added to the source and the variable I set to ngWYSIWYG on content="variable" after I click on the editor itself once more after I already see the image, then the <img> line appear on the source and the variable. If I dont click the editor again after adding image, the image will show on editor but will not get added to the variable.

**Comment by brunokrebs** [comment]
@MegazeroMZ you are right, the html generated by the editor is not getting updated after using this pasteHtmlAtCaret. I have fixed that and I will generate a patch version. By the way, I have tested on ie11, firefox, chrome and safari. They are all getting updated now.

**Comment by brunokrebs** [comment]
@MegazeroMZ this fix is merged on the master branch and it is available on [release v0.5.1](https://github.com/psergus/ngWYSIWYG/tree/v0.5.1).
