### ISSUE TITLE
Add me as a collaborator

### ISSUE THREAD

**Issue by brunokrebs** [psergus/ngWYSIWYG#44]
Hi there @psergus.

I'm wondering, would you mind adding me as a collaborator to this repo? I'm using it a lot and I think I can contribute even further if I had access to it. [This is how you add me](https://help.github.com/articles/adding-collaborators-to-a-personal-repository/), in case you approve my request.

Thanks and best regards.

**Comment by psergus** [comment]
Done and thx for coming on board +1

On Thu, Jan 28, 2016 at 5:48 AM, Bruno Krebs <notifications@github.com>
wrote:

> Hi there @psergus <https://github.com/psergus>.
>
> I'm wondering, would you mind adding me as a collaborator to this repo?
> I'm using it a lot and I think I can contribute even further if I had
> access to it. This is how you add me
> <https://help.github.com/articles/adding-collaborators-to-a-personal-repository/>,
> in case you approve my request.
>
> Thanks and best regards.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psergus/ngWYSIWYG/issues/44>.
>



-- 
Best regards,
Sergey Petrenko

**Comment by brunokrebs** [comment]
Glad to help :smile:
