### ISSUE TITLE
Bug with selecting color, background color and symbols

### ISSUE THREAD

**Issue by MegazeroMZ** [psergus/ngWYSIWYG#48]
Those 3 button, which before show a table with options to choose from are now all bugged out and show something like this (this is with all 3 of them open at once):

![wegfawegweg](https://cloud.githubusercontent.com/assets/13162201/12739643/13fc6892-c99e-11e5-82f9-9f8d2d28ac9e.png)

And just to confirm, both using the wysiwyg.min.js or manually adding all js file for me result in this.

**Comment by MegazeroMZ** [comment]
I figure out the problem. When you divided each directive into files and rename them, you forgot to rename the class in the editor.min.css. Just added "ngp-" to all colors-grid and symbols-grid class and it will be ok. Also the width of those 2 class is a little bit bigger than nessecary for some reason, so I changed width of ngp-symbols-grid class to 364px, and color class to 184px.

**Comment by brunokrebs** [comment]
Thank you very much for your help @MegazeroMZ.
