### ISSUE TITLE
Browserify, AMD, Webpack module loaders?

### ISSUE THREAD

**Issue by nkovacic** [psergus/ngWYSIWYG#49]
Currently this module loaders are not supported. 
Is this on the roadmap or can I create a pull request?

**Comment by brunokrebs** [comment]
You are more than welcome to create a pull request.

**Comment by nkovacic** [comment]
Created a pull request https://github.com/psergus/ngWYSIWYG/pull/51.

**Comment by brunokrebs** [comment]
Accepted it, thanks!

**Comment by brunokrebs** [comment]
@nkovacic by the way, would you mind writing a few lines about it on README.md?

**Comment by nkovacic** [comment]
@brunokrebs Will try this in the following week.
