### ISSUE TITLE
How to enable the font family dropdown

### ISSUE THREAD

**Issue by pdonorio** [psergus/ngWYSIWYG#60]
Maybe a dumb question, but if i use your example i don't get the second row of the bar i can see in the demo. 

I also checked the demo code and i don't see any relevant differences.

Can you point me out to what i could be missing?

Thanks for your work!

**Comment by psergus** [comment]
Hi Paolo,

would be great if you can present your example on CodePen or relative tools
so we can see the markup.

On Sun, Apr 3, 2016 at 11:27 PM, Paolo D. <notifications@github.com> wrote:

> Maybe a dump question, but if i use your example i don't get the second
> row of the bar i can see in the demo.
>
> I also checked the demo code and i don't see any relevant differences.
>
> Can you point me out to what i could be missing?
>
> Thanks for your work!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/psergus/ngWYSIWYG/issues/60>
>



-- 
Best regards,
Sergey Petrenko

**Comment by pdonorio** [comment]
Sure, i will try `codepen` as soon as i can.
Do you have a template to start with?

**Comment by pdonorio** [comment]
I am sorry, i didn't find the time to write down a CodePen script and found another solution.

The issue can be closed.
