### ISSUE TITLE
Images do not show in Firefox

### ISSUE THREAD

**Issue by msohaib47** [psergus/ngWYSIWYG#7]
Toolbar images do not render in firefox. All toolbar buttons show the first image (<>). Works in chrome.

Is there any easy fix to this?

**Comment by msohaib47** [comment]
One solution I found (but its not complete) is to replace following in tpl file

background-position-y: -XXXpx;

with

background-position: 0px -XXXpx;

This results in icons to show, but does not change icon on hover.

**Comment by innerpeace0** [comment]
I noticed this, too.

**Comment by psergus** [comment]
thx for noticing this guys. I will work on it to fix. :+1:

**Comment by phanhongphucit** [comment]
I have this too

**Comment by psergus** [comment]
released the fix guys. thx for noticing this.
