### ISSUE TITLE
Demo went blank

### ISSUE THREAD

**Issue by innerpeace0** [psergus/ngWYSIWYG#9]
It worked yesterday, and the new release looked great. Thanks.

**Comment by psergus** [comment]
glad to hear you like it :) Also, I put it on bower.

On Thu, Aug 13, 2015 at 9:05 AM, Inner Peace 0 <notifications@github.com>
wrote:

> It worked yesterday, and the new release looked great. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/psergus/ngWYSIWYG/issues/9>.
>



-- 
Best regards,
Sergey Petrenko

**Comment by psergus** [comment]
found the bug and fixed. Demo should be working now.
